// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project_l01.Api.Data;

#nullable disable

namespace Project_l01.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903100503_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project_l01.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Office equipment and supplies",
                            Name = "Office"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Office and business furniture",
                            Name = "Furniture"
                        });
                });

            modelBuilder.Entity("Project_l01.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mario.rossi@example.com",
                            FirstName = "Mario",
                            LastName = "Rossi",
                            Phone = "+39 333 1111111"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "laura.bianchi@example.com",
                            FirstName = "Laura",
                            LastName = "Bianchi",
                            Phone = "+39 333 2222222"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "luca.ferri@example.com",
                            FirstName = "Luca",
                            LastName = "Ferri",
                            Phone = "+39 333 3333333"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "giulia.romano@example.com",
                            FirstName = "Giulia",
                            LastName = "Romano",
                            Phone = "+39 333 4444444"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andrea.conti@example.com",
                            FirstName = "Andrea",
                            LastName = "Conti",
                            Phone = "+39 333 5555555"
                        });
                });

            modelBuilder.Entity("Project_l01.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_orders_total_non_negative", "\"Total\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            Status = "Completed",
                            Total = 1449.96m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            Status = "Processing",
                            Total = 629.98m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            Status = "Pending",
                            Total = 229.97m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            Status = "Completed",
                            Total = 449.93m
                        });
                });

            modelBuilder.Entity("Project_l01.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_order_items_quantity_positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_order_items_unit_price_positive", "\"UnitPrice\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1299.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 2,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 349.99m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 2,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 279.99m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 3,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 149.99m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 249.99m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 4,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 49.99m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 4,
                            ProductId = 2,
                            Quantity = 5,
                            UnitPrice = 29.99m
                        });
                });

            modelBuilder.Entity("Project_l01.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_products_price_positive", "\"Price\" > 0");

                            t.HasCheckConstraint("CK_products_stock_non_negative", "\"StockQuantity\" > 0");

                            t.HasCheckConstraint("Ck_products_minimum_stock_non_negative", "\"MinimumStock\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Professional 15-inch laptop",
                            MinimumStock = 5,
                            Name = "Laptop Pro 15",
                            Price = 1299.99m,
                            Sku = "ELEC-LAP-001",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wireless ergonomic mouse",
                            MinimumStock = 10,
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            Sku = "ELEC-MOU-001",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mechanical keyboard with backlight",
                            MinimumStock = 8,
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            Sku = "ELEC-KEY-001",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "27-inch Full HD monitor",
                            MinimumStock = 5,
                            Name = "27-inch Monitor",
                            Price = 249.99m,
                            Sku = "ELEC-MON-001",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-port USB-C hub",
                            MinimumStock = 10,
                            Name = "USB-C Hub",
                            Price = 49.99m,
                            Sku = "ELEC-HUB-001",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Large office desk",
                            MinimumStock = 3,
                            Name = "Office Desk",
                            Price = 349.99m,
                            Sku = "FURN-DES-001",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic office chair",
                            MinimumStock = 5,
                            Name = "Office Chair",
                            Price = 279.99m,
                            Sku = "FURN-CHA-001",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "LED desk lamp",
                            MinimumStock = 8,
                            Name = "Desk Lamp",
                            Price = 39.99m,
                            Sku = "OFF-LAM-001",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Metal filing cabinet",
                            MinimumStock = 3,
                            Name = "Filing Cabinet",
                            Price = 149.99m,
                            Sku = "OFF-FIL-001",
                            StockQuantity = 10
                        });
                });

            modelBuilder.Entity("Project_l01.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Project_l01.Api.Models.Order", b =>
                {
                    b.HasOne("Project_l01.Api.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Project_l01.Api.Models.OrderItem", b =>
                {
                    b.HasOne("Project_l01.Api.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_l01.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project_l01.Api.Models.Product", b =>
                {
                    b.HasOne("Project_l01.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project_l01.Api.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
